### ISSUE TITLE
Sequence of animations doesn't obey individual FPS

### ISSUE THREAD

**Issue by praxist** [ManiacalLabs/BiblioPixel#1142]
Version: 3.4.44

Using a project with the following parameters:
```
driver:
  typename: simpixel
  num: 2400

aliases:
  bpa: BiblioPixelAnimations.matrix

layout:
  typename: matrix
  width: 16
  height: 150
  brightness: 255

animation:
  typename: sequence
  length: 10
  run:
    fps: 60
    threaded: true
  animations:
    - typename: $bpa.MatrixRain.MatrixRain
      run:
        fps: 10
    - typename: $bpa.bloom.Bloom
      run:
        fps: 15
```
I would expect 60 to be the global default FPS, and for the specified animations to override that and run at 10 and 15 FPS respectively.

Instead both run at 60.
