### ISSUE TITLE
use controls to vary brightness & fps

### ISSUE THREAD

**Issue by VonHirsch** [ManiacalLabs/BiblioPixel#1147]
Hello, is it possible to use controls such as keyboard & midi to vary the overall brightness & fps of layers or animations?

For example something like this:

```
controls:
  typename: midi
  extractor:
    accept:
      type: control_change

  routing:
    0: animation.fps
    1: animation.brightness
```

I tried a few different variations of these, and I understand the routes are address identifiers, but when I look at the code i'm struggling to understand which objects & attributes are fair game to be used as routes.  Thanks.

p.s. it would be great if there was a way to generate a list of possible valid routes
