### ISSUE TITLE
mixer animation with a matrix

### ISSUE THREAD

**Issue by VonHirsch** [ManiacalLabs/BiblioPixel#1148]
Something like:

```
animation:
    typename: mixer
    levels: [0.25, 0.25]
    animations:
        - $bpa.matrix.Mainframe
        - $bpa.matrix.MatrixRain

shape: [8, 8]
```

Gives: `maximum recursion depth exceeded`

Is this a natural limitation of the mixer animation?  I tried increasing recursion limits to no avail.
